"""Update 2024-08-04

Revision ID: 068a7b71d0f1
Revises: d4a295e60439
Create Date: 2024-08-04 20:16:52.951879

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "068a7b71d0f1"
down_revision: Union[str, None] = "d4a295e60439"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
