"""Add meeting completion field

Revision ID: b360851102ce
Revises: ca18bad45236
Create Date: 2024-07-19 10:59:04.049962

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b360851102ce"
down_revision: Union[str, None] = "ca18bad45236"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "meeting_attendees",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    op.add_column(
        "meeting_recurrences", sa.Column("title", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "meeting_tasks",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    op.add_column("meetings", sa.Column("completed", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("meetings", "completed")
    op.drop_column("meeting_tasks", "created_at")
    op.drop_column("meeting_recurrences", "title")
    op.drop_column("meeting_attendees", "created_at")
    # ### end Alembic commands ###
