"""Update 2024-08-04

Revision ID: d4a295e60439
Revises: b360851102ce
Create Date: 2024-08-04 18:25:13.159628

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "d4a295e60439"
down_revision: Union[str, None] = "b360851102ce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
